spring.application.name=gestionFactures

spring.datasource.url=jdbc:mysql://localhost:3306/gestFactures?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=Syst25@@

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=1234